defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: Xinwang Liu
subtitle: Professor

# left_side:
background_image: "./assets/XinwangLiu.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"


# Side Menu Links
menu:
  - text: News
    link: /
    icon: ""

  - text: Brief Bio
    link: /Brief-Bio
    icon: ""

  - text: Under Review
    link: /Under-Review
    icon: ""

  - text: Selected Journal Papers
    link: /Selected-Journal-Papers
    icon: ""

  - text: Selected Conference Papers
    link: /Selected-Conference-Papers
    icon: ""
  
  - text: Group Members
    link: /Group-Members
    icon: ""

# Socialmedia Icons
social_icons:
  - name: mail
    link: mailto:xinwangliu@nudt.edu.cn
    icon: icon brands fa fa-envelope

  - name: google mail
    link: mailto:1022xinwang.liu@gmail.com
    icon: fab fa-google

  - name: github
    link: https://github.com/xinwangliu
    icon: fab fa-github-square


    
